[package]
name = "live-music-remover"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "live-music-remover"
path = "src/main.rs"
required-features = ["ui"]

[features]
ui = ["iced", "image_rs"]
default-model-ll = ["deep_filter/default-model-ll"]
thresholds = []
dev-console = []


[dependencies]
iced = { version = "0.12", features = [
  "image",
  "debug",
  "tokio",
  "lazy",
], optional = true }
itertools = "0.12"
crossbeam-channel = "0.5"
image_rs = { package = "image", version = "0.24", optional = true }
anyhow = "1.0"
cpal = "0.15"
clap = { version = "4.0", features = ["derive"] }
deep_filter = { path = "third_party/DeepFilterNet/libDF/", default-features = false, features = [
  "tract",
  "use-jemalloc",
  "default-model",
] }
ndarray = "^0.15"
rubato = "0.15"
ringbuf = "0.3"
env_logger = "0.10"
log = { version = "0.4", features = ["std"] }
