[package]
name = "live-music-remover"
version = "0.1.0"
edition = "2021"

description = "A real-time music remover."
license = "MIT"
repository = "https://github.com/ilyasben26/live-music-remover"
homepage = "https://github.com/ilyasben26/live-music-remover"
documentation = "https://github.com/ilyasben26/live-music-remover"

[[bin]]
name = "live-music-remover"
path = "src/main.rs"
required-features = ["ui"]

[features]
ui = ["eframe", "image_rs", "egui_extras", "egui_router"]
default-model-ll = ["deep_filter/default-model-ll"]
thresholds = []
dev-console = []


[dependencies]
eframe = { version = "0.31.1", optional = true, features = ["default"] }
egui_router = { version = "0.4", optional = true }
egui_extras = { version = "0.31", optional = true, features = ["svg"] }
itertools = "0.12"
crossbeam-channel = "0.5"
image_rs = { package = "image", version = "0.24", optional = true }
anyhow = "1.0"
cpal = "0.15"
clap = { version = "4.0", features = ["derive"] }
deep_filter = { path = "third_party/DeepFilterNet/libDF/", default-features = false, features = [
  "tract",
  "use-jemalloc",
  "default-model",
] }
ndarray = "^0.15"
rubato = "0.15"
ringbuf = "0.3"
dirs = "5"
ureq = "2"
serde_json = "1"
env_logger = "0.10"
log = { version = "0.4", features = ["std"] }
thiserror = "1.0"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_Power",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Com",
    "UI_Notifications",
    "Data_Xml_Dom",
    "Win32_System_Registry",
] }

[build-dependencies]
resvg = "0.37"
